### ISSUE TITLE
Please mention 4.02.3 instead of 4.02.2

### ISSUE THREAD

**Issue by edwintorok** [slegrand45/examples_ocsigen#1]
Please recommend 4.02.3 instead of 4.02.2 at https://github.com/slegrand45/examples_ocsigen/tree/master/jsoo/todomvc-react

4.02.2 is quite buggy with ocamlnet,libev and forking: https://github.com/ocsigen/lwt/issues/168

**Comment by slegrand45** [comment]
Thanks!
